const data = [
  {
    id: "terminalia-chebula",
    botanicalName: "Terminalia chebula",
    family: "Combretaceae",
    synonyms: [
      "Abhaya",
      "Haimavati",
      "Chetaki",
      "Shiva",
      "Rohini",
      "Pathya",
      "Putana",
    ],
    classicalCategorization: [
      "Prajasthapan",
      "Jwarghna",
      "Kusthghna",
      "Kasaghna",
      "Arsoghna(c)",
      "Triphala",
      "Aamalakyadi",
      "Parusakadi(su.)",
      "Parusakadi(v)",
    ],
    usefulPart: "Fruit rind",
    indication: [
      "Dipan",
      "Pachan",
      "Yakrit-utejak",
      "Anuloman",
      "Mridurechan",
      "Loss of appetite",
      "Pain in abdomen",
      "Constipation",
      "Ascites",
      "Heamorrhoids",
      "Rhinitis",
      "Cough",
      "Hoarseness of voice",
      "Hiccups",
      "Dyspnoea",
    ],
    shloka: [
      "हरीतकी पञ्चरसाऽलवणा तुवरा परम् ।",
      "रूक्षोष्णा दीपनी मेध्या स्वादुपाका रसायनी ॥१९॥",
      "चक्षुष्या लघुरायुष्या बृंहणी चानुलोमिनी ।",
      "श्वासकासप्रमेहार्शः कुष्ठशोथोदरक्रिमीन् ॥२०॥",
      "वैस्वर्यग्रहणीरोगविवन्धविषमज्वरान् ।",
      "गुल्माध्मानतृषाछर्दिहिक्काकण्डूहृदामयान् ॥२१।॥",
      "कामलां शूलमानाहं प्लीहानञ्च यकृत्तथा।",
      "अश्मरीं मूत्रकृच्छूञ्च मूत्राघातञ्च नाशयेत् ॥२२॥",
    ],
  },
];

module.exports = data;
