const data = [
  {
    id: "terminalia-chebula",
    botanicalName: "Terminalia chebula",
    family: "Combretaceae",
    synonyms: [
      "Abhaya",
      "Haimavati",
      "Chetaki",
      "Shiva",
      "Rohini",
      "Pathya",
      "Putana",
    ],
    classicalCategorization: [
      "Prajasthapan",
      "Jwarghna",
      "Kusthghna",
      "Kasaghna",
      "Arsoghna(c)",
      "Triphala",
      "Aamalakyadi",
      "Parusakadi(su.)",
      "Parusakadi(v)",
    ],
    usefulPart: "Fruit rind",
    indication: [
      "Dipan",
      "Pachan",
      "Yakrit-utejak",
      "Anuloman",
      "Mridurechan",
      "Loss of appetite",
      "Pain in abdomen",
      "Constipation",
      "Ascites",
      "Heamorrhoids",
      "Rhinitis",
      "Cough",
      "Hoarseness of voice",
      "Hiccups",
      "Dyspnoea",
    ],
    shloka: [
      "हरीतकी पञ्चरसाऽलवणा तुवरा परम् ।",
      "रूक्षोष्णा दीपनी मेध्या स्वादुपाका रसायनी ॥१९॥",
      "चक्षुष्या लघुरायुष्या बृंहणी चानुलोमिनी ।",
      "श्वासकासप्रमेहार्शः कुष्ठशोथोदरक्रिमीन् ॥२०॥",
      "वैस्वर्यग्रहणीरोगविवन्धविषमज्वरान् ।",
      "गुल्माध्मानतृषाछर्दिहिक्काकण्डूहृदामयान् ॥२१।॥",
      "कामलां शूलमानाहं प्लीहानञ्च यकृत्तथा।",
      "अश्मरीं मूत्रकृच्छूञ्च मूत्राघातञ्च नाशयेत् ॥२२॥",
    ],
  },
  {
    id: "pippali",
    botanicalName: "Piper longum Linn.",
    imageName:"piper-longum-linn",
    family: "Piperaceae",
    synonyms: [
      "Magadhi",
      "Vaidehi",
      "Krushna",
      "Kana",
      "Chapala",
      "Tikshnatandula",
      "Ushana Upakulya",
      "Shoundi",
    ],
    classicalCategorization: [
      "Kasahara",
      "Hikkanigharhana",
      "Vaman",
      "Truptighana",
      "Deepaniya",
      "Shoolprashamana",
    ],
    usefulPart: "Fruit",
    indications: [
      "Anorexia",
      "Loss of appetite",
      "Abdominal pain",
      "Liver disorders",
      "Spleenomegaly",
      "Worms",
      "Brain tonic",
      "Respiratory disorders",
      "Bronchial Asthma",
      "Tuberculosis",
    ],
    shloka: [
      "पिप्पली मागधी कृष्णा वैदेही चपला कणा |",
      "उपकुल्योषणा शौडी कोलाया तुण्डुला ||४९||",
      "पिप्पली दीपनी वृष्या स्वादुपाका रसायनी |",
      "अनुष्णा कटुका पित्तान्वातमहरी लघुः ||५०||",
      "पिप्पली रेचनी हिता कासकासोदरवारान् |",
      "कुमेहगुल्ममेहाशूलामवमानान् ||५१||",
      "आमाकफदाः पित्तदा शीतला मधुरा गुः |",
      "पिप्पलीशमनी सा तु शुका पिप्पलीकोपिणी ||५२||",
      "पिप्पली मधुसंयुक्ता मेदःकफविनाशनी |",
      "कासाजीर्णासितचित्ता श्लेष्मला मेहयाऽस्तिवाधनी ||५३||",
      "जीर्णवरोऽपिमार्गेण शयते गुडिपिप्पली |",
      "कासाजीर्णासितकषायवातग्रहणानि ||५४||",
    ],
  },
  {
    "id": "nadihingu",
    "botanicalName": "Gardenia gummifera Linn.",
    "imageName":"gardenia-gummifera-linn",
    "family": "Rubiaceae",
    "synonyms": ["Dikamali"],
    "usefulPart": "Niryasa",
    "indications": [
      "Dantashoola",
      "Abdominal pain",
      "Constipation",
      "Worms",
      "Anorexia",
      "Loss of appetite",
      "Indigestion",
      "Muscle pain",
      "Menstrual cycle problem"
    ]
  },
  {
    "id": "tinish",
    "botanicalName": "Ougenia oojeinensis",
    "imageName":"ougenia-oojeinensis",
    "family": "Leguminosae",
    "synonyms": ["Syandana", "Sandana", "Chanana"],
    "usefulPart": "Heart wood, Bark",
    "indications": [
      "Skin disorders",
      "Vitiligo",
      "Wound",
      "Bleeding disorders",
      "Diabetes",
      "Anemia",
      "Worms",
      "Indigestion",
      "Inflammation",
      "Liver disorders"
    ]
  },
  {
    "id": "bhandir",
    "botanicalName": "Clerodendrum infortunatum Linn.",
    "imageName":"clerodendrum-infortunatum-linn",
    "family": "Verbenaceae",
    "synonyms": ["Bhandi", "Titbhant"],
    "usefulPart": "Leaves",
    "indications": [
      "Acid peptic disorders",
      "Infected wounds",
      "Worms",
      "Fever",
      "Skin disorders",
      "Dandruff",
      "Diabetes",
      "Hypertension",
      "Bronchitis",
      "Epilepsy",
      "Tumours"
    ]
  },
  {
    "id": "guggul-sp",
    "botanicalName": "Commiphora caudata Wight & Arn",
    "imageName":"commiphora-caudata-wight-arn",
    "family": "Burseraceae",
    "synonyms": [],
    "usefulPart": "Resin",
    "indications": [
      "Mouth ulcers",
      "Wounds",
      "Rheumatoid arthritis",
      "Liver disorders",
      "Diabetes",
      "Strangury",
      "Fever"
    ]
  },
  {
    "id": "gandhaprasarini",
    "botanicalName": "Paederia foetida Linn.",
    "imageName":"paederia-foetida-linn",
    "family": "Rubiaceae",
    "synonyms": ["Prasaran", "Hiran vel"],
    "usefulPart": "Root",
    "indications": [
      "Osteoarthritis",
      "Rheumatoid arthritis",
      "Abdominal pain",
      "Gout",
      "Urinary calculi",
      "Inflammatory conditions",
      "Piles",
      "Diarrhoea"
    ]
  }
];

module.exports = data;
